OPENINSIDER_LIBNAME = openinsider_stm32f4
CPPFLAGS	+= -I$(OPENINSIDER_DIR)inc
LDFLAGS 	+= -L$(OPENINSIDER_DIR)bin
OPENINSIDER_LIBDEP	:= $(OPENINSIDER_DIR)bin/lib$(OPENINSIDER_LIBNAME).a
LIBDEPS		+= $(OPENINSIDER_LIBDEP)
LDLIBS		+= -l$(OPENINSIDER_LIBNAME)

